project/app/urls.py
from django.urls import path
from app import views

app_name = 'app'

urlpatterns = [
    path('other/',views.other,name='other'),
    path('relative/',views.relative,name='relative'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path,include
from app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
]

project/app/models.py
from django.db import models

# Create your models here.

project/app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'app/index.html')

def other(request):
    return render(request,'app/other.html')

def relative(request):
    return render(request,'app/relative.html')

project/templates/app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <ul class="navbar-nav">
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">INDEX<span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:other' %}">OTHER</a>
                  </li>
          </ul>
        </div>
      </nav>

      <div class="container">
        {% block body_block %}

        {% endblock %}
      </div>
  </body>
</html>

project/templates/app/index.html
<!DOCTYPE html>
{% extends "app/base.html" %}
  {% block body_block %}

      <h1>INDEX</h1>

  {% endblock %}

project/templates/app/other.html
<!DOCTYPE html>
{% extends "app/base.html" %}
  {% block body_block %}
  <h1>OTHER</h1>
  {% endblock %}

project/templates/app/relative.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>RELATIVE</title>
  </head>
  <body>
<h1>RELATIVE</h1>
<a href="{% url 'app:other' %}"> OTHER </a>
  </body>
</html>